### ISSUE TITLE
Build initial Watchtower Client

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/watchtower.starknet.id#1]
See https://app.skiff.com/file/cab5aed0-f072-4e18-9754-393e9937f498

The Watchtower Client, built with Next.js, serves as a user-friendly interface to view and monitor StarknetID logs. It allows users to filter and sort log entries effectively. Additionally, it allows to create and remove jwt tokens used by services to log information.

**Comment by fricoben** [comment]
Done
